<a href="https://colab.research.google.com/github/rburakkorkmaz/CSE-406_Scientific-Programming/blob/main/Korkmaz_RamazanBurak_EX4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><strong>Exercise 4</strong></h1>
<h1><strong>Student Name & Surname:</strong> Ramazan Burak Korkmaz</h1>
<h1><strong>Student ID:</strong> 202151056004</h1>

<h2>Needed packages</h2>

In [1]:
import numpy as np
import time

In [57]:
# Function to check if given matrix is Toeplitz.
# It was not asked in the exercise. I just use it
# to debugging
def isToeplitz(matrix):
    temp = list(matrix)
    # base case
    if not temp:
        return True
 
    for i in range(len(temp) - 1):
        for j in range(len(temp[0]) - 1):
            if temp[i][j] != temp[i + 1][j + 1]:
                return False
 
    return True

<h2>Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix</h2>

In [59]:
N = 200
M = 300

# Create A matrix
A = np.random.normal(size=(N, M))

# Create B Matrix
B_row = np.random.rand(1, M*2)
B = np.empty((0, M))

for i in range(0, M):
  B = np.append(B, B_row[:, :M], axis = 0)
  B_row = np.roll(B_row, 1)


In [60]:
A.shape

(200, 300)

In [61]:
B.shape

(300, 300)

In [62]:
isToeplitz(B)

True

<h1><strong>Exercise 9.1:</strong> Matrix operations</h1>
Calculate A + A, AAT, ATA and AB.  Write a function that computes A(B − λI) for any λ.


In [63]:
A+A

array([[-0.70454012, -0.35734186, -2.77046916, ...,  0.74097443,
         0.37839309, -0.20175506],
       [-1.38769293,  1.88967816,  1.12238009, ..., -0.67005426,
        -0.501799  , -1.83023404],
       [ 1.6272957 ,  3.28582184,  1.18067787, ...,  1.29249107,
        -0.25549283,  1.11956523],
       ...,
       [-3.21835182, -0.25401583, -2.12134323, ..., -0.66850709,
        -0.37832811,  2.002575  ],
       [-2.99806772, -0.6830963 , -0.8761254 , ...,  1.5434886 ,
         2.41290236, -3.44189675],
       [ 5.46208977,  1.16085232, -3.10006872, ..., -0.87926726,
        -1.17941972,  4.89788647]])

In [64]:
np.matmul(A, A.T)

array([[310.27781726,  24.77283429, -12.3291704 , ...,  34.97149675,
          7.30381841,   0.83309681],
       [ 24.77283429, 268.91308696,   5.72265363, ...,   7.93178994,
         10.68373992,  -0.34619784],
       [-12.3291704 ,   5.72265363, 278.20521533, ...,  -4.95583231,
         -1.27857796, -19.72009675],
       ...,
       [ 34.97149675,   7.93178994,  -4.95583231, ..., 279.12205465,
         28.44701142,   6.26561563],
       [  7.30381841,  10.68373992,  -1.27857796, ...,  28.44701142,
        284.74563098, -18.43502889],
       [  0.83309681,  -0.34619784, -19.72009675, ...,   6.26561563,
        -18.43502889, 302.25880264]])

In [65]:
np.matmul(A, B)

array([[  3.11320558,  -0.0301465 ,   0.51131343, ...,   5.93086156,
         10.73854236,   7.16844864],
       [  1.21138779,   1.33233574,   2.33921499, ...,   4.32578165,
         -0.16029908,   6.17281475],
       [ 13.31504463,   9.67120753,  16.49469878, ...,   6.39910452,
          3.34014524,  19.04116823],
       ...,
       [  2.52780338, -10.37179877,  -1.8612019 , ...,   4.76576481,
          6.56673964,   9.25062483],
       [  4.87904142,   4.39231062,  15.91173364, ...,   7.64020683,
          9.44283739,  11.6215776 ],
       [  8.50879871,  19.62933499,  15.25762528, ...,   8.28155041,
          9.17823164,  10.3392895 ]])

In [66]:
def func_to_solve(A, B, L):
  return np.matmul(A, (B - L*np.identity(len(B))))

In [67]:
func_to_solve(A, B, 2)

array([[  3.8177457 ,   0.32719536,   3.2817826 , ...,   5.18988713,
         10.36014927,   7.3702037 ],
       [  2.59908071,  -0.55734242,   1.2168349 , ...,   4.99583591,
          0.34149992,   8.00304879],
       [ 11.68774893,   6.38538569,  15.31402091, ...,   5.10661345,
          3.59563807,  17.921603  ],
       ...,
       [  5.74615519, -10.11778294,   0.26014133, ...,   5.4342719 ,
          6.94506775,   7.24804983],
       [  7.87710915,   5.07540692,  16.78785904, ...,   6.09671822,
          7.02993504,  15.06347435],
       [  3.04670894,  18.46848267,  18.357694  , ...,   9.16081766,
         10.35765136,   5.44140303]])

<h1><strong>Exercise 9.2:</strong> Solving a linear system</h1>
Generate a vector b with m entries and solve Bx = b.



In [68]:
b = np.random.rand(M, 1)

In [69]:
b.shape

(300, 1)

In [70]:
B_inv = np.linalg.inv(B)
X = np.matmul(B_inv, b)

In [71]:
X.shape

(300, 1)

<h1><strong>Exercise 9.3:</strong> Norms</h1>
Compute the Frobenius norm of A:||A||F and the infinity norm of B:||B||∞.  Also find the largest and smallest singular values of B.




In [72]:
A_norm = np.linalg.norm(A, ord=None)
B_norm = np.linalg.norm(B, ord=np.inf)
largest_singular_values = np.linalg.norm(B, ord = 2)
smallest_singular_values = np.linalg.norm(B, ord = -2)

In [73]:
A_norm

245.72184865699964

In [74]:
B_norm

151.63485548161674

In [75]:
largest_singular_values

147.89879973117434

In [76]:
smallest_singular_values

0.02278433995912373

<h1><strong>Exercise 9.4:</strong> Power iteration</h1>
Generate  a  matrix  Z,  n      n,  with  Gaussian  entries,  and  use  the  power  iteration  to find  the  largest eigenvalue and corresponding eigenvector of Z.  How many iterations are needed till convergence?

Optional:  use the time.clock() method to compare computation time when varying n.





In [77]:
def power_method(Z, start_lambda, tolerate):
  # Initial matrix
  v = np.ones((len(Z), 1))

  # List that holds last two lambda values, so we can calculate error
  lambda_history = [0, start_lambda]

  # Initializing error variable
  error = abs(lambda_history[-1] - lambda_history[0])

  # Variable to count loop numbers
  counter = 0

  # Start time variable that holds when loop started
  start = time.time()

  # COnvering loop. Each iteration we get close to the real eigenvector values
  while error > tolerate:
    v = np.matmul(Z, v)
    lambda_history = [lambda_history[-1], max(abs(v))]
    v = v / lambda_history[-1]
    error = abs(lambda_history[-1] - lambda_history[0])
    counter += 1
  
  # Calcualte elapsed time in while loop
  elapsed_time = time.time() - start

  print(f"Elapsed time: {elapsed_time}")
  print(f"Loop count: {counter}")
  return elapsed_time, counter, v

In [78]:
Z = np.random.normal(size=(N, N))
elapsed_time, loop_counter, a = power_method(Z, 1, 0.001)

Elapsed time: 2.9385650157928467
Loop count: 8764


In [79]:
a

array([[ 0.18258929],
       [-0.3944868 ],
       [-0.5720586 ],
       [ 0.13386498],
       [-0.1096334 ],
       [-0.21811183],
       [-0.15493372],
       [ 0.14838403],
       [ 0.19517958],
       [ 0.73119567],
       [-0.09191164],
       [ 0.24777669],
       [ 0.0015    ],
       [ 0.26036879],
       [ 0.15879646],
       [-0.45480748],
       [ 0.60918933],
       [-0.18233682],
       [ 0.45113962],
       [-0.03079444],
       [-0.24582891],
       [ 0.51328521],
       [ 0.30929607],
       [ 0.32211753],
       [ 0.18150775],
       [-0.41086958],
       [-0.02144664],
       [ 0.27835171],
       [ 0.20498957],
       [ 0.09894573],
       [-0.11445256],
       [-0.00261156],
       [-0.55470555],
       [-0.21716259],
       [-0.12735365],
       [-0.05912227],
       [-0.10881907],
       [-0.74641148],
       [-0.29514283],
       [-0.23161464],
       [ 0.35844746],
       [-0.08611628],
       [-0.20810092],
       [ 0.07807671],
       [ 0.05316798],
       [ 0

<h1><strong>Exercise 9.6:</strong> Nearest neighbor</h1>
Write a function that takes a value z and an array A and finds the element in A that is closest to 
z.  The function should return the closest value, not index.
Hint:  Use the built-in functionality of Numpy rather than writing code to find this value 
manually.  In particular, use brackets and argmin.






In [80]:
def find_nearest_neighbor(z, A):
  # Create a matrix that has same dimensions with matrix A and each element of
  # this matrix is z
  z_matrix = z*np.ones((len(A), len(A)))

  # Subtract z matrix from A and apply absolute to all elements
  # This way we can know distance between each element of A with z
  temp = abs(A - z_matrix)

  # By using argmin function, simply find smallest distance in the temp matrix
  # Smallest distance's index is the nearest neighbor
  row, column = np.unravel_index(np.argmin(temp, axis=None), temp.shape)
  return A[row][column]

In [81]:
A = np.array([[10, 30, 53],
              [72,  1,  3],
              [4,  32, 21]])

find_nearest_neighbor(28, A)

30